name: Crous Room Checker

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:        # Allow manual run

jobs:
  check_rooms:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # auto-kills the job if it runs longer than 5 mins
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run alert script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          CITY_FILTER: ${{ secrets.CITY_NAME }}
        run: |
            echo "Starting script at $(date)"
            python alert.py
            echo "Script completed at $(date)"
